title: Mohamed Alaa Abdelhamed
description: Computer engineering student.
show_downloads: true
theme: jekyll-theme-cayman
github:  zip_url: https://www.linkedin.com/in/mohamed-alaa-806a5a266/  another_url: another value
