title: Mohamed Alaa Abdelhamed
description: Computer Engineering Student.
Phone Number +201200709954  
[mohamed.alaa2985@gmail.com](mailto:mohamed.alaa2985@gmail.com)  
[LinkedIn Profile](https://www.linkedin.com/in/mohamed-alaa-806a5a266)
show_downloads: false
theme: jekyll-theme-cayman

